services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${APP_USER}
      APP_USER_PASSWORD: ${APP_USER_PASSWORD}
      # ORACLE_DATABASE: mydb # Uncomment to set a specific database
    ports:
      - "1521:1521"
