services:
  oracle:
    image: gvenzl/oracle-free:slim
    container_name: oracle
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${APP_USER}
      APP_USER_PASSWORD: ${APP_USER_PASSWORD}
      # ORACLE_DATABASE: mydb # Uncomment to set a specific database
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: